# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restemailuser',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name=b'name'),
            preserve_default=False,
        ),
    ]
